### PR TITLE
fix: prevent action issues caused by `a` element wrapping post component

### LINKED ISSUE #70: [Bug]: can't perform `Post` actions from homepage
### What happened?

image

here, because of the `a` element wrapping this [`Post`](https://github.com/quibble-dev/Quibble/blob/8741491f387571cd5fd3bf921470a3fa00ed2fcf/frontend/src/lib/components/pages/home/post.svelte#L24-L25) component, cant perform actions like- 'like', 'dislike', 'share', etc.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by daaniissh**
close #70

### CODE REVIEW

File: frontend/src/lib/components/pages/home/post.svelte [hunk 1]
```diff
@@ -28,33 +34,36 @@
...
 	<p class="line-clamp-3 text-sm font-normal text-base-content" class:hidden={props.cover}>
 		{props.content}
 	</p>
+
 	<img class="rounded-xl" src={props.cover} alt="" />
-	<div class="mt-2 flex gap-4">
-		<div class="flex items-center gap-2">
+
+	<div class="mt-2 block-link flex gap-4">
+		<div on:click={stopEventPropagation} class="flex items-center gap-2">
```
Comment (moonlitgrace) [inline frontend/src/lib/components/pages/home/post.svelte:50]: `onclick`

File: frontend/src/lib/components/pages/home/post.svelte [hunk 2]
```diff
@@ -19,6 +19,12 @@
 	};
 
 	let props: Props = $props();
+
+	// Correctly stop the propagation and prevent default behavior
+	function stopEventPropagation(e: Event) {
+		e.stopPropagation();
+		e.preventDefault();
+	}
```
Comment (moonlitgrace) [inline frontend/src/lib/components/pages/home/post.svelte:27]: https://svelte.dev/docs/svelte/v5-migration-guide#Event-changes-Event-modifiers
should be able to pass functions, also move it to lib/functions

**Review by moonlitgrace — CHANGES_REQUESTED** [review]
hey @daaniissh, thanks, also can you check failed action details?

File: frontend/src/lib/functions/propegation.ts
Comment (moonlitgrace) [inline frontend/src/lib/functions/propegation.ts:1]: rename filename it to `event-modifiers.ts`
and function to `stopPropagation`

**Review by moonlitgrace — CHANGES_REQUESTED** [review]

**Comment by moonlitgrace** [comment]
also @daaniissh, after checking it locally, seems like this is not how it should work.
this just prevent the propagation, sorry not that i meant.

check this how reddit is doing it:
image
there seems like an absolute `a` element, and tweak z-index so that post options gets above em'.
can you implement this?

**Review by moonlitgrace — APPROVED** [review]
